module.exports = {
  appName: "AutoAtende",
  botVersion: "2.5.0",
  botAdmin: "5516996509803@s.whatsapp.net",
  botCountryCode: "55",
  botDDDCode: "16",
  doNotHandleNumbers: [ '5516981251080','5517981436608', '5516992916444','5516991121744',
                        '5516993739942','553197137788','551637213315','5517992133812',
                        '5516993710273','5516994184493','5516981303311','5516991131877',
                        '13109418333','5516994579554','5517996235872','5516992895991',
                        '5516994622366','5511950825321','5516999803888','5516982626317',
                        '5516993259097','5519999088888','5511972522364','5516991252590',
                        '5516992877187','5516997980088','5516996180725','5516992552268',
                        '5516992243371','5516992734181','5516992974914','5516988310481', 
                        '5516991251039','5516993203850','5516992304095','5511940632372',
                        '5516994639264', '5516997152093'],
  diasSemana: [
    'Domingo',
    'Segunda-Feira',
    'Terça-Feira',
    'Quarta-Feira',
    'Quinta-Feira',
    'Sexta-Feira',
    'Sabado',
  ],
  emojiMap: {
    0: '🤖',
    1: '🕗', 
    2: '👀',
    3: '🗺',
    4: '⌛',
    5: '😋',
    6: '💲',
    7: '🛎',
    8: '🙋‍♂️'
  },
  // Lista de comandos permitidos
  atalhos: [
    'entrega',
    'retirada',
    'bloqueia',
    'desbloqueia',
    'bot',
    'status',
    'stats',
    'oi',
    'bv',
    'pix',
    'cardapio',
    'endereco',
    'horario',
    'backup',
    'ajuda',
    'massas'
  ],
  palavrasChave: [
    'queijo', 'mussarela', 'quatro queijos', '4 queijos', '4 queijo',
    'parisiense', 'parisense',
    'cheddar e bacon', 'cheddar e bacon', 'chedar e bacon', 'cheddar bacon', 'bacon', 'chedar', 'cheddar',
    'broccoli', 'brocolis', 'brócolis',
    'ao sugo', 'aosugo', 'sugo',
    'bolonhesa', 'bolonhesa', 'bolonheza', 'bolonheza', 'carne', 'moida',
    'ragu de costela', 'ragu de costela', 'ragu costela', 'ragu costela', 'ragu', 'costela',
    'camarão', 'camarão', 'camarao',
    'camarão rosé', 'camarão rosé', 'camarao rose', 'camarão rose',
    'funghi', 'funghi', 'fungi', 'cogumelos', 'cogumelo',
    'risoto', 'risoto', 'rizoto',
    'nhoque', 'nhoque', 'gnocchi', 'nhoke', 'nhoque tradicional',
    'nhoque recheado', 'nhoque recheado', 'gnocchi recheado', 'nhoke recheado',
    'macarrão', 'macarrão', 'macarrao', 'massa',
    'talharim', 'talharim', 'talharin', 'talharin',
    'caracolino', 'caracolino', 'caracolinho',
    'penne', 'penne', 'pene',
    'penne integral', 'penne integral', 'pene integral',
    'coca', 'cola', 'coca-cola lata', 'coca cola lata', 'coca lata', 'lata',
    'coca-cola 2lt', 'coca-cola 2lt', 'coca cola 2lt', 'coca 2lt',
    'coca-cola zero', 'coca-cola zero', 'coca cola zero', 'coca zero',
    'guaraná', 'guarana', 'guaraná antartica lata', 'guaraná lata', 'guarana lata',
    'guaraná antartica litro', 'guaraná antartica litro', 'guaraná litro', 'guarana litro',
    'suco spress', 'suco spress', 'suco press', 'suko spress', 'suco', 'laranja', 'uva',
    'energético monster', 'energético monster', 'energetico monster', 'energético monstro', 'energetico', 'energético', 'redbull',
    'fanta laranja', 'fanta laranja', 'fanta laraja', 'fanta laranga', 'fanta',
    'água mineral', 'água mineral', 'agua mineral',
    'água mineral com gás', 'água mineral com gás', 'agua mineral com gas', 'agua', 'água',
    'água foors 500 ml', 'água foors 500 ml', 'agua foors 500 ml',
    'água foors 1 litro', 'água foors 1 litro', 'agua foors 1 litro',
    'água fors de 2 litros', 'água fors de 2 litros', 'agua fors de 2 litros',
  ], 
  mostrarMsgEntregaReduzida: false,
  numMaxMsgMkt: 150,
  mostrarAjuda: false,
  mostrarRestSuper: false,
  mostrarValeRefeicoes: true,
  numOfDaysOff: 30,
  tempoEntreMensagens: 1500,
  maxAgeForGraphs: 3600000,
  maxAgeForSessions: 24 * 60 * 60 * 1000, 
  legendaRestSuper: `Obrigado Franca ❤️`,
  msgMkt: `🍝🍝 *Combo Queridinho* 🥤🎉\n\nApresentando o Combo Queridinho da Ital'in House por apenas R$74,90 + taxa de entrega! 😋\n\n*Este combo incrível inclui:*\n2 Boxes de Macarrão com 800 gramas. 🍝🍝\n1 Guaraná de 1 Litro 🥤\nPerfeito para uma refeição deliciosa e prática em casa. Peça agora e deixe-nos cuidar do almoço! 🚀🏠\n\n*Para realizar um pedido basta clicar no link abaixo:* 👇\nhttps://rebrand.ly/italin_franca02\n\n#ComidaDeliciosa #ComboQueridinho #EntregaRápida #Ital'inHouse`,
  msgBV: `🤩 Olá 👋!\nBem vindo à Ital'in House! 💚🤍❤️🍝🧑🏼‍🍳`,
  msgBV0: `🤩 Olá, {{pushname}} 👋!\nBem vindo à Ital'in House! 💚🤍❤️🍝🧑🏼‍🍳`,
  msgBV1: `Digite a opção desejada:\n1️⃣ - Ver horários de funcionamento 🕗\n2️⃣ - Ver Cárdapio 👀\n3️⃣ - Nossa localização 🗺\n4️⃣ - Tempo para entregar ⌛\n5️⃣ - Fazer um pedido 😋\n6️⃣ - Ver opções de pagamento 💲\n7️⃣ - Opções de consumo/entrega 🛎\n8️⃣ - Falar com um atendente 🙋‍♂️\n\n⚠️ Se tiver alguma dúvida digite ajuda.\n💥 Para ver a promoção do dia, digite promoção.`,
  msgBV2: `Para realizar um pedido basta clicar no link abaixo: 👇\n{{enderecoCardapio}}\n\nSe precisar *MESMO* da ajuda de um atendente, envie 8 e aguarde, ok?`,
  msgLojaFechada: "Boas vindas à Ital'in House! 💚🤍❤️🍝🧑🏼‍🍳\n\n*Nossa loja está fechada.*\n",
  msgAvisoBot: "⚠️ Nós usamos um robô para atendimento de WhatsApp. quando você recebe a mensagem acima, com os números de 1 a 8, caso não queira ser atendido pelo robô, por gentileza informe 8 para falar com um atendente.",
  msgAtendente: "⚠️ Você já solicitou atendimento. Por favor, aguarde um momento. Obrigado!",
  msgAvisoAtendente: "🙋‍♂️ Um atendente logo estará disponível para te ajudar. Aguarde um momento. Obrigado!",
  msgReforcoCliente: `👋 Olá, novamente! Parece que você está explorando nosso atendimento virtual. Se precisar de ajuda com nosso cardápio delicioso ou quiser fazer um pedido, é só me chamar! Estou aqui para tornar sua experiência na Ital'in House incrível. 😊🍝🥂\n\nSe você tiver qualquer dúvida, envie 8 e aguarde, ok?`,
  msgEntregaReduzida: `🍝🏙️ Descubra a Ital'In House no bairro Cidade Nova! Nossos deliciosos pratos de macarrão estão a poucos passos de você. E tem mais: se você mora nos bairros da zona NORTE, NORDESTE ou NOROESTE, aproveite nossas taxas de entrega reduzidas. 🛵🤑`,
  msgMotoEntrega: `🤩 Olá 👋! Passando pra dizer que seu pedido já esta pronto.\nSe tiver qualquer problema, pode me enviar aqui mesmo, ou nos ligar no telefone (16) 99788-8800 para resolvermos imediatamente.\n\nE se tiver gostado, a sua avaliação nos ajuda MUITO a crescer, e se destacar entre tantos.\n\nEstamos participando de uma competição, e se nos der 5 estrelas, nos deixará mais próximo de vencer ! ✨\n\nO SEU FEEDBACK SERÁ SEMPRE MUITO IMPORTANTE PARA NÓS.\n\nMil vezes obrigado!\nItal'in House! 💚🤍❤️🍝🧑🏼‍🍳\n\nAhh, outra coisa… Se puder, nos marque como “favoritos”, assim você receberá promoções exclusivas 😍🍝`,
  msgAvisoSegundas: "☝🏼 *Aviso:* As segundas-feiras a Loja01 da Ital'in House Franca funciona em outra localização. 📁\n\nRua Alvaro Abranches, 1057 - Cidade Nova, Franca/SP",
  msgMassas: "💚🤍❤️🍝🧑🏼‍🍳 *Escolha sua massa.*",
  empresa: {
    nomeDaLoja: "Ital'in House Franca Loja 02",
    enderecoDaLoja: "Rua Alváro Abranches, 1057, Cidade Nova, Franca-SP, CEP 14401-094",
    enderecoCardapio: "https://rebrand.ly/italin_franca02",
    botNumber: "5516997888800@s.whatsapp.net",
    latitude: "-20.524254149322978",
    longitude: "-47.39218863060321",
    horariosFuncionamento: "⏰ Nossos horários de funcionamento são:\n\n*Domingo* das 11:00h às 23:00h.\n\n*Segunda* das 11:00h às 23:00h.\n\n*Terça* das 11:00h às 14:00h e das 18:00h às 23:00h.\n\n*Quarta* das 11:00 às 14:00 e das 18:00h às 23:00h.\n\n*Quinta* das 11:00 às 14:00 e das 18:00h às 23:00h.\n\n*Sexta* das 11:00 às 23:00h.\n\n*Sábado* das 11:00 às 23:00h",
    verCardapio: "☝🏼 Nosso cardápio.\nNem consigo te recomendar um prato, porque eu amo todos! 😍\n\nLembrando que nossos box vem 800g de um delicioso macarrão gourmet e 650g de um maravilhoso risoto.\n\nPara pedir, acesse:\nhttps://rebrand.ly/italin_franca02\n\n🤤A Ital'in House agradece a preferência, bom apetite 😀🤌🏼🍝",
    verCardapio01: "☝🏼 Nosso cardápio.\nPara pedir, acesse:\nhttps://rebrand.ly/italin_franca02\n\n🤤A Ital'in House agradece a preferência, bom apetite 😀🤌🏼🍝",
    nossaLocalizacao: "📍 Um momento, vou te encaminhar nosso *endereço* e *telefone*... 📁\n\nRua Alvaro Abranches, 1057 - Cidade Nova, Franca/SP, CEP: 14401-094.\n\nSe preferir, você também pode ver pelo Maps! 🗺️👇\nhttps://goo.gl/maps/2B9tKHBARb2qsVS37\n\n*Contato*\n📱 (16) 99788-8800",
    tempoParaEntregar: "⏱️ O nosso tempo de *retirada* é de 10 à 25 minutos, já o nosso tempo de *entrega* é de 15 à 30 minutos.",
    fazerPedido: "🍽️ O cardápio está no link abaixo, o que escolher chega na hora pra mim! 👇\n\nhttps://rebrand.ly/italin_franca02",
    opcoesPagamento: "💲 Opções de pagamento:\n\n💰 Dinheiro\n\n💳 Cartões Débito ou Crédito\n✔️ Visa\n✔️ Elo\n✔️ Mastercard\n\n💳 Cartões Vale Refeição\n\n📲 Pagamento por Pix\n🔑 Chave Celular: 1699788-8800\nM.W. Foods LTDA.",
    opcoesRetirada: "😋 Você pode receber o seu pedido das seguintes formas:\n- Entrega (Delivery) 🛵\n- Retirada no local (Takeway)🚗",
    legendaPagamentos: "*Cartões Vale Refeição*",
    pedidoProntoRetirada: "Notícia boa 🤩\nSeu pedido está pronto, é só vir buscar.\nMuito obrigado, bom apetite e uma super semana.\n📍 Rua Alvaro Abranches, 1057 - Cidade Nova, Franca/SP",
    pedidoSaiuParaEntrega: "🛵 Seu pedido acaba de sair para entrega.\nAgradecemos a preferência! Muito obrigado, bom apetite e uma super semana. Esperamos você para experimentar outros molhos novamente em breve. 😀🥰",
    msgClientesInativos: "🍝🍷 Olá amante da culinária italiana! Sentimos sua falta na ItalinHouse! 😊\n\nRelembrando nossos pratos deliciosos: Quatro Queijos, Parisiense, Cheddar e Bacon, Ao Sugo, Bolonhesa e mais! Opções de massa: Talharim, Penne, Nhoque e mais. Risotos também disponíveis.\n\n📣 Aproveite para pedir e desfrutar de uma refeição italiana autêntica. Entre em contato pelo WhatsApp: +55 16 99788 8800. Esperamos te atender em breve!\nItal'in House! 💚🤍❤️🍝🧑🏼‍🍳",
    chavePix: "*Chave Celular:* _16997888800_ *Nome:* _M.W.Foods Ltda_",
  },
  promocoes: {
    sabado: "Promoção de sabádo - Combo QUERIDINHO por apenas R$74,90",
    domingo: "Promoção de sabádo - Combo QUERIDINHO por apenas R$74,90",
    segunda: "Promoção de segunda-feira - Combo MATCH GOURMET por apenas R$37,90",
    terca: "Promoção de terça-feira - Combo SABOR SUCESSO por apenas R$37,90",
    quarta: "Promoção de segunda-feira - Combo MATCH GOURMET por apenas R$37,90",
    quinta: "Promoção de quinta-feira - Combo SABOR SUCESSO por apenas R$37,90",
    sexta: "Promoção de segunda-feira - Combo MATCH GOURMET por apenas R$37,90"
  },
  tiposDeLogradouros: [
    "rua",
    "avenida",
    "travessa",
    "praça",
    "quadra",
    "alameda",
    "beco",
    "vila",
    "estrada", 
    "passagem",
    "viela",
    "servidão"
  ],
  cmdArray: ['0','1','2','3','4','5','6','7','8'],
  timeZone: {
    area: "America/Sao_Paulo",
    value: "-03:00",
  },
  showLog: true,
  sendDevLog: true,
  sendServerStatusDevMsg: true,
  devNumber: `5516996509803@s.whatsapp.net`,
  errorMsgs: {
    startCore: "Ocorreu um erro ao iniciar a instrução startCore()",
  },
  messages: [
    "🍰 *Novidade na Ital'in House!* Tiramisú por apenas R$16,90 🍰😋\n\n*Para realizar um pedido basta clicar no link abaixo:* 👇\nhttps://rebrand.ly/italin_franca02\n\n",
    "💚🤍❤️🍝🧑🏼‍🍳 Na Ital'in House, celebramos o Halloween o dia inteiro com o dobro de queijo! 🎃🧀 Uma delícia assustadoramente irresistível que você pode desfrutar a qualquer hora. Trick or cheese! 🕒",
    "⚠️ *Atenção ao horário de funcionamento.*",
  ],
  ajuda: [
    "🤩 Olá 👋!\nBem vindo à Ital'in House! 💚🤍❤️🍝🧑🏼‍🍳.\nPara tornar sua experiência mais fácil e conveniente, oferecemos um menu com oito opções.\nPor favor, escolha a opção desejada digitando o número correspondente. Aqui estão as opções disponíveis e para quem serve cada opção:",
    "1️⃣ *- Ver horários de funcionamento 🕗:*\nOlá! Você pode verificar nossos horários de funcionamento digitando o número 1 ou escrevendo horarios.",
    "2️⃣ *- Ver Cardápio 👀:*\nQue tal explorar nosso cardápio? Basta digitar o número 2 ou escrever cardapio. Tenho informações detalhadas sobre nossas deliciosas opções!",
    "3️⃣ *- Nossa localização 🗺:*\nQuer saber onde estamos localizados? É fácil! Digite o número 3 ou escreva endereço. Estou pronto para compartilhar nossos detalhes.",
    "4️⃣ *- Tempo para entregar ⌛:*\nCurioso sobre o tempo de entrega? Basta digitar o número 4 ou escrever tempo para saber o tempo estimado para receber seu pedido.",
    "5️⃣ *- Fazer um pedido 😋:*\nPronto para fazer um pedido delicioso? É só digitar o numero 5 ou escrever pedido. Vou ajudar você a fazer o pedido rapidamente!",
    "6️⃣ *- Ver opções de pagamento 💲:*\nPara conferir nossas opções de pagamento, digite o número 6 ou escreva pagamento. Estou aqui para esclarecer suas dúvidas.",
    "7️⃣ *- Opções de consumo/entrega 🛎:*\nSe deseja saber mais sobre nossas opções de consumo ou métodos de entrega, digite o número 7 ou escreva entrega. Estou à disposição!",
    "8️⃣ *- Falar com um atendente 🙋‍♂️:*\nSe você preferir falar diretamente com um atendente, você está no lugar certo! Digite o número 8 ou escreva atendente e você será conectado com nossa equipe.",
    "Se você continuar com dúvidas, digite 8 e um atendente irá lhe ajudar. Queremos tornar sua experiência conosco a melhor possível.\n🤤A Ital'in House agradece a preferência, bom apetite 😀🤌🏼🍝",
  ],
  ajudaOp: `ℹ️ *Comando de Ajuda* ℹ️\n\nVocê pode usar os seguintes comandos:\n\n- *!entrega*: Notifica que o pedido saiu para entrega.\n- *!retirada*: Notifica que o pedido está pronto para retirada.\n- *!bloqueia*: Adiciona o número à lista de exclusão.\n- *!desbloqueia*: Remove o número da lista de exclusão.\n- *!bot*: Notifica o uso do robô.\n- *!backup*: Realiza um backup do banco de dados.\n- *!bloqueia*: Adiciona o número à lista de exclusão.\n- *!desbloqueia*: Remove o número da lista de exclusão.\n- *!status*: Verifica o status do servidor.\n- *!pix*: Recebe a chave PIX da empresa.\n- *!stats*: Obtém estatísticas e relatórios.\n- *!oi*: Recebe uma saudação do bot.\n- *!bv*: Recebe mensagens de boas-vindas.\n- *!cardápio*: Mostra o cardápio.\n- *!endereco*: Mostra o endereço da loja.\n- *!horario*: Mostra os horários de funcionamento da loja.\n\nEspero que isso tenha ajudado! 😊`,
  enableKeywordDetector: true,
  enableAddrDetector: false,
  enableStats: true,
  enableStatus: true,
  enableEmogiReact: true,
  enableLocalCache: false,
  enableDB: true,
  autoTurnOff: false,
  showMondayInfo: false,
  dir: {
    backup: "bkp",
    cache: "cache",
    charts: "chart",
    images: "img",
    session: "session",
    reports: "reports"
  },
  modules: {
    bbn: true,
  },
  datasource: {
    data: {
      dialect: "mariadb",
      host: "localhost",
      db: "italin_db",
      user: "italinbot",
      pwd: "Brx2045rb@",
      log: false,
    },
    ispaid: {
      dialect: "mysql",
      host: "154.56.48.154",
      db: "u276801829_clientes",
      user: "u276801829_italinbot",
      pwd: "?qOi6jM7r6",
      log: false,
    }
  },
  _cmdPoints: {
      1: 2,
      2: 10,
      3: 8,
      4: 2,
      5: 15,
      6: 10,
      7: 5,
      8: 1,
  }
};
