module.exports = {
<<<<<<< Updated upstream
  "botVersion": "2.1.3",
  "botAdmin": "5516993636362@s.whatsapp.net",
  "botCountryCode": "55",
  "botDDDCode": "16",
  "doNotHandleNumbers": [
    "5516993710273",
    "5516994184493",
    "5516981303311",
    "5516991131877",
    "13109418333",
    "5516994579554",
    "5517996235872",
    "5516992895991",
    "553197137788",
    "5516994622366",
    "5517981436608",
    "5511950825321",
    "5516993259097",
    "5519999088888",
    "5511972522364",
    "5516999803888",
    "5516992877187",
    "5516997888800",
    "5516996180725",
    "5516992552268",
    "5516992243371",
    "5516992734181",
    "5516992974914",
    "5516988310481",
    "5516991251039",
    "5516993203850",
    "5516992304095",
    "5511940632372",
    "5516982626317",
    "551637213315",
    "5517992133812"
  ],
  "diasSemana": [
=======
  botVersion: "2.1.6",
  botAdmin: "5516996509803@s.whatsapp.net",
  botCountryCode: "55",
  botDDDCode: "16",
  diasSemana: [
>>>>>>> Stashed changes
    "Domingo",
    "Segunda-Feira",
    "Terça-Feira",
    "Quarta-Feira",
    "Quinta-Feira",
    "Sexta-Feira",
    "Sabado"
  ],
<<<<<<< Updated upstream
  "emojiMap": {
    "0": "🤖",
    "1": "🕗",
    "2": "👀",
    "3": "🗺",
    "4": "⌛",
    "5": "😋",
    "6": "💲",
    "7": "🛎",
    "8": "🙋‍♂️"
  },
  "atalhos": [
=======
  emojiMap: {
    0: "🤖",
    1: "🕗",
    2: "👀",
    3: "🗺",
    4: "⌛",
    5: "😋",
    6: "💲",
    7: "🛎",
    8: "🙋‍♂️"
  },
  atalhos: [
>>>>>>> Stashed changes
    "entrega",
    "retirada",
    "bloqueia",
    "desbloqueia",
    "bot",
    "status",
    "stats",
    "oi",
    "bv",
<<<<<<< Updated upstream
    "cardapio"
  ],
  "palavrasChave": {
    "quatro queijos": [
      "queijo",
      "mussarela",
      "quatro queijos",
      "4 queijos",
      "4 queijo"
    ],
    "parisiense": [
      "parisiense",
      "parisense"
    ],
    "cheddar e bacon": [
      "cheddar e bacon",
      "chedar e bacon",
      "cheddar bacon",
      "bacon",
      "chedar",
      "cheddar"
    ],
    "broccoli": [
      "broccoli",
      "brocolis",
      "brócolis"
    ],
    "ao sugo": [
      "ao sugo",
      "aosugo",
      "sugo"
    ],
    "bolonhesa": [
      "bolonhesa",
      "bolonheza",
      "bolonheza",
      "carne",
      "moida"
    ],
    "ragu de costela": [
      "ragu de costela",
      "ragu costela",
      "ragu costela",
      "ragu",
      "costela"
    ],
    "camarão": [
      "camarão",
      "camarao"
    ],
    "camarão rosé": [
      "camarão rosé",
      "camarao rose",
      "camarão rose"
    ],
    "funghi": [
      "funghi",
      "fungi",
      "cogumelos",
      "cogumelo"
    ],
    "risoto": [
      "risoto",
      "rizoto"
    ],
    "nhoque": [
      "nhoque",
      "gnocchi",
      "nhoke",
      "nhoque tradicional"
    ],
    "nhoque recheado": [
      "nhoque recheado",
      "gnocchi recheado",
      "nhoke recheado"
    ],
    "macarrão": [
      "macarrão",
      "macarrao",
      "massa"
    ],
    "talharim": [
      "talharim",
      "talharin",
      "talharin"
    ],
    "caracolino": [
      "caracolino",
      "caracolinho"
    ],
    "penne": [
      "penne",
      "pene"
    ],
    "penne integral": [
      "penne integral",
      "pene integral"
    ],
    "coca-cola lata": [
      "coca",
      "cola",
      "coca-cola lata",
      "coca cola lata",
      "coca lata"
    ],
    "coca-cola 2lt": [
      "coca-cola 2lt",
      "coca cola 2lt",
      "coca 2lt"
    ],
    "coca-cola zero": [
      "coca-cola zero",
      "coca cola zero",
      "coca zero"
    ],
    "guaraná antartica lata": [
      "guaraná",
      "guarana",
      "guaraná antartica lata",
      "guaraná lata",
      "guarana lata"
    ],
    "guaraná antartica litro": [
      "guaraná antartica litro",
      "guaraná litro",
      "guarana litro"
    ],
    "suco spress": [
      "suco spress",
      "suco press",
      "suko spress",
      "suco",
      "laranja",
      "uva"
    ],
    "energético monster": [
      "energético monster",
      "energetico monster",
      "energético monstro",
      "energetico",
      "energético",
      "redbull"
    ],
    "fanta laranja": [
      "fanta laranja",
      "fanta laraja",
      "fanta laranga",
      "fanta"
    ],
    "água mineral": [
      "água mineral",
      "agua mineral"
    ],
    "água mineral com gás": [
      "água mineral com gás",
      "agua mineral com gas"
    ],
    "água foors 500 ml": [
      "água foors 500 ml",
      "agua foors 500 ml"
    ],
    "água foors 1 litro": [
      "água foors 1 litro",
      "agua foors 1 litro"
    ],
    "água fors de 2 litros": [
      "água fors de 2 litros",
      "agua fors de 2 litros"
    ]
  },
  "mostrarMsgEntregaReduzida": false,
  "numMaxMsgMkt": 50,
  "mostrarAjuda": false,
  "mostrarRestSuper": false,
  "numOfDaysOff": 30,
  "tempoEntreMensagens": 1000,
  "legendaRestSuper": "Obrigado Franca ❤️",
  "msgMkt": "🍝🍝 *Combo Queridinho* 🥤🎉\n\nApresentando o Combo Queridinho da Ital'in House por apenas R$74,90 + taxa de entrega! 😋\n\n*Este combo incrível inclui:*\n2 Boxes de Macarrão com 800 gramas. 🍝🍝\n1 Guaraná de 1 Litro 🥤\nPerfeito para uma refeição deliciosa e prática em casa. Peça agora e deixe-nos cuidar do almoço! 🚀🏠\n\n*Para realizar um pedido basta clicar no link abaixo:* 👇\nhttps://rebrand.ly/italin_franca02\n\n#ComidaDeliciosa #ComboQueridinho #EntregaRápida #Ital'inHouse",
  "msgBV": "🤩 Olá 👋!\nBem vindo à Ital'in House! 💚🤍❤️🍝🧑🏼‍🍳",
  "msgBV0": "🤩 Olá, {{pushname}} 👋!\nBem vindo à Ital'in House! 💚🤍❤️🍝🧑🏼‍🍳",
  "msgBV1": "Digite a opção desejada:\n1️⃣ - Ver horários de funcionamento 🕗\n2️⃣ - Ver Cárdapio 👀\n3️⃣ - Nossa localização 🗺\n4️⃣ - Tempo para entregar ⌛\n5️⃣ - Fazer um pedido 😋\n6️⃣ - Ver opções de pagamento 💲\n7️⃣ - Opções de consumo/entrega 🛎\n8️⃣ - Falar com um atendente 🙋‍♂️",
  "msgBV2": "Para realizar um pedido basta clicar no link abaixo: 👇\n{{enderecoCardapio}}\n\nSe precisar *MESMO* da ajuda de um atendente, envie \"*8*\" e aguarde, ok?",
  "msgLojaFechada": "Boas vindas à Ital'in House! 💚🤍❤️🍝🧑🏼‍🍳\n\n*Nossa loja está fechada.*\n",
  "msgAvisoBot": "⚠️ Nós usamos um robô para atendimento de WhatsApp. quando você recebe a mensagem acima, com os números de 1 a 8, caso não queira ser atendido pelo robô, por gentileza informe *8* para falar com um atendente.",
  "msgAtendente": "⚠️ Você já solicitou atendimento. Por favor, aguarde um momento. Obrigado!",
  "msgAvisoAtendente": "🙋‍♂️ Um atendente logo estará disponível para te ajudar. Aguarde um momento. Obrigado!",
  "msgReforcoCliente": "👋 Olá, novamente! Parece que você está explorando nosso atendimento virtual. Se precisar de ajuda com nosso cardápio delicioso ou quiser fazer um pedido, é só me chamar! Estou aqui para tornar sua experiência na Ital'in House incrível. 😊🍝🥂\n\nSe você tiver qualquer dúvida, envie \"8\" e aguarde, ok?",
  "msgEntregaReduzida": "🍝🏙️ Descubra a Ital'In House no bairro Cidade Nova! Nossos deliciosos pratos de macarrão estão a poucos passos de você. E tem mais: se você mora nos bairros da zona NORTE, NORDESTE ou NOROESTE, aproveite nossas taxas de entrega reduzidas. 🛵🤑",
  "msgMotoEntrega": "🤩 Olá 👋! Passando pra dizer que seu pedido já esta pronto.\nSe tiver qualquer problema, pode me enviar aqui mesmo, ou nos ligar no telefone (16) 99788-8800 para resolvermos imediatamente.\n\nE se tiver gostado, a sua avaliação nos ajuda MUITO a crescer, e se destacar entre tantos.\n\nEstamos participando de uma competição, e se nos der 5 estrelas, nos deixará mais próximo de vencer ! ✨\n\nO SEU FEEDBACK SERÁ SEMPRE MUITO IMPORTANTE PARA NÓS.\n\nMil vezes obrigado!\nItal'in House! 💚🤍❤️🍝🧑🏼‍🍳\n\nAhh, outra coisa… Se puder, nos marque como “favoritos”, assim você receberá promoções exclusivas 😍🍝",
  "empresa": {
    "nomeDaLoja": "Ital'in House Franca Loja 01",
    "enderecoDaLoja": "Rua Emília Scalabrini, 5055, Residencial José de Carlos, Franca-SP",
    "enderecoCardapio": "https://rebrand.ly/italin_franca01",
    "botNumber": "5516997980088@s.whatsapp.net",
    "latitude": "-20.562240203007526",
    "longitude": "-47.36965987483271",
    "horariosFuncionamento": "⏰ Nossos horários de funcionamento são:\n\n*Domingo* das 11:00h às 23:00h.\n\n*Segunda* das 11:00h às 23:00h.\n\n*Terça* das 11:00h às 23:00h.\n\n*Quarta* das 11:00 às 23:00h.\n\n*Quinta* das 11:00 às 23:00h.\n\n*Sexta* das 11:00 às 23:00h.\n\n*Sábado* das 11:00 às 23:00h",
    "verCardapio": "☝🏼 Nosso cardápio.\nNem consigo te recomendar um prato, porque eu amo todos! 😍\n\nLembrando que nossos box vem 800g de um delicioso macarrão gourmet e 650g de um maravilhoso risoto.\n\n🤤A Ital'in House agradece a preferência, bom apetite 😀🤌🏼🍝",
    "nossaLocalizacao": "📍 Um momento, vou te encaminhar nosso *endereço* e *telefone*... 📁\n\nRua Emilia Scalabrini, 5055 - Residêncial José de Carlos, Franca/SP\n\nSe preferir, você também pode ver pelo Maps! 🗺️👇\nhttps://goo.gl/maps/m1H3yEABetJzPvEZ8\n\n*Contato*\n📱 (16) 99798-0088",
    "tempoParaEntregar": "⏱️ O nosso tempo de *retirada* é de 10 à 25 minutos, já o nosso tempo de *entrega* é de 15 à 30 minutos.",
    "fazerPedido": "🍽️ O cardápio está no link abaixo, o que escolher chega na hora pra mim! 👇\n\nhttps://rebrand.ly/italin_franca01",
    "opcoesPagamento": "💲 Opções de pagamento:\n\n💰 Dinheiro\n\n💳 Cartões Débito ou Crédito\n\t✔️ Visa\n\t✔️ Elo\n\t✔️ Mastercard\n\n💳 Cartões Vale Refeição\n\n📲 Pagamento por Pix\n\t🔑 Chave Celular: 1699798-0088\n\tM.W. Foods LTDA.",
    "opcoesRetirada": "😋 Você pode receber o seu pedido das seguintes formas:\n- Entregas 🛵\n- Retirada de pedidos no local 🚗",
    "legendaPagamentos": "*Cartões Vale Refeição*",
    "pedidoProntoRetirada": "Notícia boa 🤩\nSeu pedido está pronto, é só vir buscar.\nMuito obrigado, bom apetite e uma super semana.\n📍 Rua Emília Scalabrini, 5055 - Residencial José de Carlos, Franca/SP",
    "pedidoSaiuParaEntrega": "🛵 Seu pedido acaba de sair para entrega.\nAgradecemos a preferência! Muito obrigado, bom apetite e uma super semana. Esperamos você para experimentar outros molhos novamente em breve. 😀🥰",
    "msgClientesInativos": "🍝🍷 Olá amante da culinária italiana! Sentimos sua falta na ItalinHouse! 😊\n\nRelembrando nossos pratos deliciosos: Quatro Queijos, Parisiense, Cheddar e Bacon, Ao Sugo, Bolonhesa e mais! Opções de massa: Talharim, Penne, Nhoque e mais. Risotos também disponíveis.\n\n📣 Aproveite para pedir e desfrutar de uma refeição italiana autêntica. Entre em contato pelo WhatsApp: +55 16 99798 0088. Esperamos te atender em breve!\nItal'in House! 💚🤍❤️🍝🧑🏼‍🍳"
  },
  "tiposDeLogradouros": [
=======
    "cardapio",
    "backup",
    "endereco",
    "ajuda",
  ],
  palavrasChave: [
    "queijo",
    "mussarela",
    "quatro queijos",
    "4 queijos",
    "4 queijo",
    "parisiense",
    "parisense",
    "cheddar e bacon",
    "cheddar e bacon",
    "chedar e bacon",
    "cheddar bacon",
    "bacon",
    "chedar",
    "cheddar",
    "broccoli",
    "brocolis",
    "brócolis",
    "ao sugo",
    "aosugo",
    "sugo",
    "bolonhesa",
    "bolonhesa",
    "bolonheza",
    "bolonheza",
    "carne",
    "moida",
    "ragu de costela",
    "ragu de costela",
    "ragu costela",
    "ragu costela",
    "ragu",
    "costela",
    "camarão",
    "camarão",
    "camarao",
    "camarão rosé",
    "camarão rosé",
    "camarao rose",
    "camarão rose",
    "funghi",
    "funghi",
    "fungi",
    "cogumelos",
    "cogumelo",
    "risoto",
    "risoto",
    "rizoto",
    "nhoque",
    "nhoque",
    "gnocchi",
    "nhoke",
    "nhoque tradicional",
    "nhoque recheado",
    "nhoque recheado",
    "gnocchi recheado",
    "nhoke recheado",
    "macarrão",
    "macarrão",
    "macarrao",
    "massa",
    "talharim",
    "talharim",
    "talharin",
    "talharin",
    "caracolino",
    "caracolino",
    "caracolinho",
    "penne",
    "penne",
    "pene",
    "penne integral",
    "penne integral",
    "pene integral",
    "coca",
    "cola",
    "coca-cola lata",
    "coca cola lata",
    "coca lata",
    "lata",
    "coca-cola 2lt",
    "coca-cola 2lt",
    "coca cola 2lt",
    "coca 2lt",
    "coca-cola zero",
    "coca-cola zero",
    "coca cola zero",
    "coca zero",
    "guaraná",
    "guarana",
    "guaraná antartica lata",
    "guaraná lata",
    "guarana lata",
    "guaraná antartica litro",
    "guaraná antartica litro",
    "guaraná litro",
    "guarana litro",
    "suco spress",
    "suco spress",
    "suco press",
    "suko spress",
    "suco",
    "laranja",
    "uva",
    "energético monster",
    "energético monster",
    "energetico monster",
    "energético monstro",
    "energetico",
    "energético",
    "redbull",
    "fanta laranja",
    "fanta laranja",
    "fanta laraja",
    "fanta laranga",
    "fanta",
    "água mineral",
    "água mineral",
    "agua mineral",
    "água mineral com gás",
    "água mineral com gás",
    "agua mineral com gas",
    "agua",
    "água",
    "água foors 500 ml",
    "água foors 500 ml",
    "agua foors 500 ml",
    "água foors 1 litro",
    "água foors 1 litro",
    "agua foors 1 litro",
    "água fors de 2 litros",
    "água fors de 2 litros",
    "agua fors de 2 litros"
  ],
  mostrarMsgEntregaReduzida: false,
  numMaxMsgMkt: 50,
  mostrarAjuda: false,
  mostrarRestSuper: false,
  numOfDaysOff: 30,
  tempoEntreMensagens: 1000,
  legendaRestSuper: "Obrigado Franca ❤️",
  msgMkt: "🍝🍝 *Combo Queridinho* 🥤🎉\n\nApresentando o Combo Queridinho da Ital'in House por apenas R$74,90 + taxa de entrega! 😋\n\n*Este combo incrível inclui:*\n2 Boxes de Macarrão com 800 gramas. 🍝🍝\n1 Guaraná de 1 Litro 🥤\nPerfeito para uma refeição deliciosa e prática em casa. Peça agora e deixe-nos cuidar do almoço! 🚀🏠\n\n*Para realizar um pedido basta clicar no link abaixo:* 👇\nhttps://rebrand.ly/italin_franca02\n\n#ComidaDeliciosa #ComboQueridinho #EntregaRápida #Ital'inHouse",
  msgBV: "🤩 Olá 👋!\nBem vindo à Ital'in House! 💚🤍❤️🍝🧑🏼‍🍳",
  msgBV0: "🤩 Olá, {{pushname}} 👋!\nBem vindo à Ital'in House! 💚🤍❤️🍝🧑🏼‍🍳",
  msgBV1: "Digite a opção desejada:\n1️⃣ - Ver horários de funcionamento 🕗\n2️⃣ - Ver Cárdapio 👀\n3️⃣ - Nossa localização 🗺\n4️⃣ - Tempo para entregar ⌛\n5️⃣ - Fazer um pedido 😋\n6️⃣ - Ver opções de pagamento 💲\n7️⃣ - Opções de consumo/entrega 🛎\n8️⃣ - Falar com um atendente 🙋‍♂️",
  msgBV2: "Para realizar um pedido basta clicar no link abaixo: 👇\n{{enderecoCardapio}}\n\nSe precisar *MESMO* da ajuda de um atendente, envie \"*8*\" e aguarde, ok?",
  msgLojaFechada: "Boas vindas à Ital'in House! 💚🤍❤️🍝🧑🏼‍🍳\n\n*Nossa loja está fechada.*\n",
  msgAvisoBot: "⚠️ Nós usamos um robô para atendimento de WhatsApp. quando você recebe a mensagem acima, com os números de 1 a 8, caso não queira ser atendido pelo robô, por gentileza informe *8* para falar com um atendente.",
  msgAtendente: "⚠️ Você já solicitou atendimento. Por favor, aguarde um momento. Obrigado!",
  msgAvisoAtendente: "🙋‍♂️ Um atendente logo estará disponível para te ajudar. Aguarde um momento. Obrigado!",
  msgReforcoCliente: "👋 Olá, novamente! Parece que você está explorando nosso atendimento virtual. Se precisar de ajuda com nosso cardápio delicioso ou quiser fazer um pedido, é só me chamar! Estou aqui para tornar sua experiência na Ital'in House incrível. 😊🍝🥂\n\nSe você tiver qualquer dúvida, envie \"8\" e aguarde, ok?",
  msgEntregaReduzida: "🍝🏙️ Descubra a Ital'In House no bairro Cidade Nova! Nossos deliciosos pratos de macarrão estão a poucos passos de você. E tem mais: se você mora nos bairros da zona NORTE, NORDESTE ou NOROESTE, aproveite nossas taxas de entrega reduzidas. 🛵🤑",
  msgMotoEntrega: "🤩 Olá 👋! Passando pra dizer que seu pedido já esta pronto.\nSe tiver qualquer problema, pode me enviar aqui mesmo, ou nos ligar no telefone (16) 99788-8800 para resolvermos imediatamente.\n\nE se tiver gostado, a sua avaliação nos ajuda MUITO a crescer, e se destacar entre tantos.\n\nEstamos participando de uma competição, e se nos der 5 estrelas, nos deixará mais próximo de vencer ! ✨\n\nO SEU FEEDBACK SERÁ SEMPRE MUITO IMPORTANTE PARA NÓS.\n\nMil vezes obrigado!\nItal'in House! 💚🤍❤️🍝🧑🏼‍🍳\n\nAhh, outra coisa… Se puder, nos marque como “favoritos”, assim você receberá promoções exclusivas 😍🍝",
  msgAvisoSegundas: "☝🏼 *Aviso:* As segundas-feiras a Loja01 da Ital'in House Franca funciona em outra localização. 📁\n\nRua Alvaro Abranches, 1057 - Cidade Nova, Franca/SP",
  empresa: {
    nomeDaLoja: "Ital'in House Franca Loja 01",
    enderecoDaLoja: "Rua Emília Scalabrini, 5055, Residencial José de Carlos, Franca-SP, CEP: 14403-831",
    enderecoCardapio: "https://rebrand.ly/italin_franca01",
    botNumber: "5516997980088@s.whatsapp.net",
    latitude: "-20.562240203007526",
    longitude: "-47.36965987483271",
    horariosFuncionamento: "⏰ Nossos horários de funcionamento são:\n\n*Domingo* das 11:00h às 23:00h.\n\n*Segunda* das 11:00h às 23:00h.\n\n*Terça* das 11:00h às 23:00h.\n\n*Quarta* das 11:00 às 23:00h.\n\n*Quinta* das 11:00 às 23:00h.\n\n*Sexta* das 11:00 às 23:00h.\n\n*Sábado* das 11:00 às 23:00h",
    verCardapio: "☝🏼 Nosso cardápio.\nNem consigo te recomendar um prato, porque eu amo todos! 😍\n\nLembrando que nossos box vem 800g de um delicioso macarrão gourmet e 650g de um maravilhoso risoto.\n\n🤤A Ital'in House agradece a preferência, bom apetite 😀🤌🏼🍝",
    nossaLocalizacao: "📍 Um momento, vou te encaminhar nosso *endereço* e *telefone*... 📁\n\nRua Emilia Scalabrini, 5055 - Residêncial José de Carlos, Franca/SP, CEP: 14403-831\n\nSe preferir, você também pode ver pelo Maps! 🗺️👇\nhttps://goo.gl/maps/m1H3yEABetJzPvEZ8\n\n*Contato*\n📱 (16) 99798-0088",
    tempoParaEntregar: "⏱️ O nosso tempo de *retirada* é de 10 à 25 minutos, já o nosso tempo de *entrega* é de 15 à 30 minutos.",
    fazerPedido: "🍽️ O cardápio está no link abaixo, o que escolher chega na hora pra mim! 👇\n\nhttps://rebrand.ly/italin_franca01",
    opcoesPagamento: "💲 Opções de pagamento:\n\n💰 Dinheiro\n\n💳 Cartões Débito ou Crédito\n\t✔️ Visa\n\t✔️ Elo\n\t✔️ Mastercard\n\n💳 Cartões Vale Refeição\n\n📲 Pagamento por Pix\n\t🔑 Chave Celular: 1699798-0088\n\tM.W. Foods LTDA.",
    opcoesRetirada: "😋 Você pode receber o seu pedido das seguintes formas:\n- Entregas 🛵\n- Retirada de pedidos no local 🚗",
    legendaPagamentos: "*Cartões Vale Refeição*",
    pedidoProntoRetirada: "Notícia boa 🤩\nSeu pedido está pronto, é só vir buscar.\nMuito obrigado, bom apetite e uma super semana.\n📍 Rua Emília Scalabrini, 5055 - Residencial José de Carlos, Franca/SP",
    pedidoSaiuParaEntrega: "🛵 Seu pedido acaba de sair para entrega.\nAgradecemos a preferência! Muito obrigado, bom apetite e uma super semana. Esperamos você para experimentar outros molhos novamente em breve. 😀🥰",
    msgClientesInativos: "🍝🍷 Olá amante da culinária italiana! Sentimos sua falta na ItalinHouse! 😊\n\nRelembrando nossos pratos deliciosos: Quatro Queijos, Parisiense, Cheddar e Bacon, Ao Sugo, Bolonhesa e mais! Opções de massa: Talharim, Penne, Nhoque e mais. Risotos também disponíveis.\n\n📣 Aproveite para pedir e desfrutar de uma refeição italiana autêntica. Entre em contato pelo WhatsApp: +55 16 99798 0088. Esperamos te atender em breve!\nItal'in House! 💚🤍❤️🍝🧑🏼‍🍳"
  },
  tiposDeLogradouros: [
>>>>>>> Stashed changes
    "rua",
    "avenida",
    "travessa",
    "praça",
    "quadra",
    "alameda",
    "beco",
    "vila",
    "estrada",
    "passagem",
    "viela",
    "servidão"
  ],
<<<<<<< Updated upstream
  "cmdArray": [
=======
  cmdArray: [
>>>>>>> Stashed changes
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8"
  ],
<<<<<<< Updated upstream
  "timeZone": "America/Sao_Paulo",
  "showLog": false,
  "sendDevLog": true,
  "sendServerStatusDevMsg": true,
  "devNumber": "5516993636362@s.whatsapp.net",
  "errorMsgs": {
    "startCore": "Ocorreu um erro ao iniciar a instrução startCore()"
  },
  "enableKeywordDetector": true,
  "enableAddrDetector": false,
  "enableStats": false,
  "enableEmogiReact": true,
  "enableDB": false,
  "chartDir": "chart",
  "msgAvisoSegundas": "☝🏼 *Aviso:* As segundas-feiras a Loja01 da Ital'in House Franca funciona em outra localização. 📁\n\nRua Alvaro Abranches, 1057 - Cidade Nova, Franca/SP"
=======
  timeZone: "America/Sao_Paulo",
  showLog: false,
  sendDevLog: true,
  sendServerStatusDevMsg: true,
  devNumber: "5516993636362@s.whatsapp.net",
  errorMsgs: {
    startCore: "Ocorreu um erro ao iniciar a instrução startCore()"
  },
  enableKeywordDetector: true,
  enableAddrDetector: false,
  enableStats: true,
  enableEmogiReact: true,
  enableDB: true,
  chartDir: "chart",
  enableStatus: true,
  bkpDir: "bkp",
  doNotHandleNumbers: [
    "553197137788",
    "5516993710273",
    "5516994184493",
    "5516981303311",
    "5516991131877",
    "13109418333",
    "5516994579554",
    "5517996235872",
    "5516992895991",
    "5516994622366",
    "5517981436608",
    "5511950825321",
    "5516993259097",
    "5519999088888",
    "5511972522364",
    "5516999803888",
    "5516992877187",
    "5516997980088",
    "5516996180725",
    "5516992552268",
    "5516992243371",
    "5516992734181",
    "5516992974914",
    "5516988310481",
    "5516991251039",
    "5516993203850",
    "5516992304095",
    "5511940632372",
    "5516982626317",
    "551637213315",
    "5517992133812",
    "5516991252590"
  ],
  autoTurnOff: false
>>>>>>> Stashed changes
};